Repository Gongju-Unity-Bootcamp/SUIKA-GAME, pull requests merged in 2023-11, with the labels that each got.

#4 Update Introduce README.md File
  README.md
Labels: enhancement

#3 Update Introduce README.md File 2
  README.md
Labels: enhancement

#14 Add Shooter Logic And Create Demo Planet Prefab
  First Team/Assets/Physics.meta
  First Team/Assets/Physics/Planet.physicsMaterial2D
  First Team/Assets/Physics/Planet.physicsMaterial2D.meta
  First Team/Assets/Prefabs/Planet.meta
  First Team/Assets/Prefabs/Planet/Jupiter.prefab
  First Team/Assets/Prefabs/Planet/Jupiter.prefab.meta
  First Team/Assets/Scenes/Ingame.unity
  First Team/Assets/Scenes/Title.unity
  First Team/Assets/Scripts/ShooterController.cs
  First Team/Assets/Scripts/ShooterController.cs.meta
  First Team/Assets/Scripts/TAEBAEK font.otf
  First Team/Assets/Scripts/TAEBAEK font.otf.meta
  First Team/ProjectSettings/TagManager.asset
Labels: enhancement

#17 GAMEOVER UI
  First Team/Assets/GameoverTitile.cs
  First Team/Assets/GameoverTitile.cs.meta
  First Team/Assets/Scenes/GameOver.unity
  First Team/Assets/Scenes/GameOver.unity.meta
  First Team/Assets/Scripts/GAMEOVER Text.cs
  First Team/Assets/Scripts/GAMEOVER Text.cs.meta
Labels: enhancement

#18 Add Hexagon Grid for Planet
  First Team/Assets/Physics/Planet.physicsMaterial2D
  First Team/Assets/Prefabs/Planet/Jupiter.prefab
  First Team/Assets/Scenes/Ingame.unity
  First Team/Assets/Scripts/GridController.cs
  First Team/Assets/Scripts/GridController.cs.meta
  First Team/Assets/Scripts/PlanetController.cs
  First Team/Assets/Scripts/PlanetController.cs.meta
  First Team/Assets/Scripts/ShooterController.cs
  First Team/ProjectSettings/TagManager.asset
Labels: bug

#20 Modify UI Setting And Connect All Scenes
  First Team/Assets/GameoverTitile.cs
  First Team/Assets/GameoverTitile.cs.meta
  First Team/Assets/Physics/Planet.physicsMaterial2D
  First Team/Assets/Scenes/GameOver.unity
  First Team/Assets/Scripts/GameOverTextEffect.cs
  First Team/Assets/Scripts/GameOverTextEffect.cs.meta
Labels: enhancement

#24 Add Planet Physics Logic
  SUIKA-GAME/Assets/Physics/Planet.physicsMaterial2D
  SUIKA-GAME/ProjectSettings/Physics2DSettings.asset
Labels: enhancement

#26 게임 슈터 로직변경
  SUIKA-GAME/Assets/Prefabs/Planet/Mercury.prefab
  SUIKA-GAME/Assets/Prefabs/Planet/Mercury.prefab.meta
  SUIKA-GAME/Assets/Scenes/Ingame.unity
  SUIKA-GAME/Assets/Scripts/MercuryController.cs
  SUIKA-GAME/Assets/Scripts/MercuryController.cs.meta
  SUIKA-GAME/Assets/Scripts/ShooterController.cs
Labels: bug, enhancement

#28 Add Game Shooter Logic and Fix Shooter Move
  SUIKA-GAME/Assets/Scenes/Ingame.unity
  SUIKA-GAME/Assets/Scripts/ShooterController.cs
Labels: enhancement

#29 Motify Files
  SUIKA-GAME/Assets/Scenes/Ingame.unity
  SUIKA-GAME/Assets/Scripts/GameManager.cs
  SUIKA-GAME/Assets/Scripts/GameManager.cs.meta
  SUIKA-GAME/Assets/Scripts/Mercury.cs
  SUIKA-GAME/Assets/Scripts/Mercury.cs.meta
Labels: duplicate

#31 프리펩 제작 및 레벨링 시스템 구현
  SUIKA-GAME/Assets/Prefabs/Planet/1.Mercury.prefab
  SUIKA-GAME/Assets/Prefabs/Planet/1.Mercury.prefab.meta
  SUIKA-GAME/Assets/Prefabs/Planet/2.Venus.prefab
  SUIKA-GAME/Assets/Prefabs/Planet/2.Venus.prefab.meta
  SUIKA-GAME/Assets/Prefabs/Planet/3.Earth.prefab
  SUIKA-GAME/Assets/Prefabs/Planet/3.Earth.prefab.meta
  SUIKA-GAME/Assets/Prefabs/Planet/4.Mars.prefab
  SUIKA-GAME/Assets/Prefabs/Planet/4.Mars.prefab.meta
  SUIKA-GAME/Assets/Prefabs/Planet/5.Jupiter.prefab
  SUIKA-GAME/Assets/Prefabs/Planet/5.Jupiter.prefab.meta
  SUIKA-GAME/Assets/Prefabs/Planet/6.Saturn.prefab
  SUIKA-GAME/Assets/Prefabs/Planet/6.Saturn.prefab.meta
  SUIKA-GAME/Assets/Prefabs/Planet/7.Uranus.prefab
  SUIKA-GAME/Assets/Prefabs/Planet/7.Uranus.prefab.meta
  SUIKA-GAME/Assets/Prefabs/Planet/8.Neptune.prefab
  SUIKA-GAME/Assets/Prefabs/Planet/8.Neptune.prefab.meta
  SUIKA-GAME/Assets/Prefabs/Planet/9.Sun.prefab
  SUIKA-GAME/Assets/Prefabs/Planet/9.Sun.prefab.meta
  SUIKA-GAME/Assets/Scenes/Ingame.unity
  SUIKA-GAME/Assets/Scripts/GameManager.cs
  SUIKA-GAME/Assets/Scripts/Mercury.cs
  SUIKA-GAME/Assets/Scripts/Planet.cs
  SUIKA-GAME/Assets/Scripts/Planet.cs.meta
  SUIKA-GAME/Assets/Scripts/PlanetGameObjects.cs
  SUIKA-GAME/Assets/Scripts/PlanetGameObjects.cs.meta
  SUIKA-GAME/Assets/Scripts/ShooterController.cs
  SUIKA-GAME/Assets/Sprites/Sun.png
  SUIKA-GAME/Assets/Sprites/Sun.png.meta
Labels: bug, duplicate, enhancement

#33 Modify Planet Collision Detact Logic
  SUIKA-GAME/Assets/Physics/Planet.physicsMaterial2D
  SUIKA-GAME/Assets/Prefabs/Planet/1.Mercury.prefab
  SUIKA-GAME/Assets/Prefabs/Planet/2.Venus.prefab
  SUIKA-GAME/Assets/Prefabs/Planet/3.Earth.prefab
  SUIKA-GAME/Assets/Prefabs/Planet/4.Mars.prefab
  SUIKA-GAME/Assets/Prefabs/Planet/5.Jupiter.prefab
  SUIKA-GAME/Assets/Prefabs/Planet/6.Saturn.prefab
  SUIKA-GAME/Assets/Prefabs/Planet/7.Uranus.prefab
  SUIKA-GAME/Assets/Prefabs/Planet/8.Neptune.prefab
  SUIKA-GAME/Assets/Scenes/Ingame.unity
  SUIKA-GAME/Assets/Scripts/Planet.cs
  SUIKA-GAME/Assets/Scripts/PlanetGameObjects.cs
  SUIKA-GAME/Assets/Scripts/ShooterController.cs
Labels: bug, enhancement

#34 Modify README.md file
  README.md
Labels: documentation

#35 Modify Planet Collision Detact
  SUIKA-GAME/Assets/Scripts/Planet.cs
Labels: bug

#37 Fix Planet Collision Detact Logic
  SUIKA-GAME/Assets/Scripts/Planet.cs
Labels: enhancement

#38 Merge ShooterController
  SUIKA-GAME/Assets/Scripts/ShooterController.cs
Labels: duplicate

#40 게임오버 라인 로직 구현 및 게임오버 화면 송출 구현
  SUIKA-GAME/Assets/Prefabs/Planet/9.Sun.prefab
  SUIKA-GAME/Assets/Scenes/Ingame.unity
  SUIKA-GAME/Assets/Scripts/GameOverLineManager.cs
  SUIKA-GAME/Assets/Scripts/GameOverLineManager.cs.meta
  SUIKA-GAME/Assets/Scripts/Planet.cs
  SUIKA-GAME/Assets/Scripts/PlanetGameObjects.cs
  SUIKA-GAME/ProjectSettings/EditorBuildSettings.asset
Labels: bug, enhancement

#42 Change GameOver Line Logic
  SUIKA-GAME/Assets/Scripts/GameOverLineManager.cs
Labels: duplicate, enhancement

#44 Modify Repogitory Files
  SUIKA-GAME/Assets/Scripts/GameOverLineManager.cs
  SUIKA-GAME/Assets/Scripts/Planet.cs
  SUIKA-GAME/Assets/Scripts/ShooterController.cs
Labels: duplicate

#46 게임오버라인 기능 구현 마무리
  SUIKA-GAME/Assets/Scenes/Ingame.unity
  SUIKA-GAME/Assets/Scripts/GameOverLineManager.cs
Labels: enhancement

#47 Modify Planet Check Line Logic
  SUIKA-GAME/Assets/Scripts/GameOverLineManager.cs
Labels: duplicate, enhancement

#50 Update Ingame Scene
  SUIKA-GAME/Assets/Scenes/Ingame.unity
  SUIKA-GAME/Assets/Scripts/GameOverLineManager.cs
Labels: enhancement

#52 Modify Planet Collider Scale
  SUIKA-GAME/Assets/Prefabs/Planet/1.Mercury.prefab
  SUIKA-GAME/Assets/Prefabs/Planet/2.Venus.prefab
  SUIKA-GAME/Assets/Prefabs/Planet/3.Earth.prefab
  SUIKA-GAME/Assets/Prefabs/Planet/4.Mars.prefab
  SUIKA-GAME/Assets/Prefabs/Planet/5.Jupiter.prefab
  SUIKA-GAME/Assets/Prefabs/Planet/6.Saturn.prefab
  SUIKA-GAME/Assets/Prefabs/Planet/7.Uranus.prefab
  SUIKA-GAME/Assets/Prefabs/Planet/8.Neptune.prefab
Labels: bug, enhancement

#54 코드의 이해를 돕기위해 주석과 스코어UI 제작중
  SUIKA-GAME/Assets/Scripts/GameOverTextEffect.cs
  SUIKA-GAME/Assets/Scripts/Planet.cs
  SUIKA-GAME/Assets/Scripts/ScoreManager.cs
  SUIKA-GAME/Assets/Scripts/ScoreManager.cs.meta
  SUIKA-GAME/Assets/Scripts/ShooterController.cs
Labels: documentation, duplicate

#57 게임 스코어UI 구현
  SUIKA-GAME/Assets/Scenes/GameOver.unity
  SUIKA-GAME/Assets/Scenes/Ingame YS.unity
  SUIKA-GAME/Assets/Scripts/ScoreManager.cs
Labels: enhancement

#59 Merge Repogitory Files In TestScene
  SUIKA-GAME/Assets/Scenes/GameOver.unity
  SUIKA-GAME/Assets/Scenes/Ingame.unity
Labels: duplicate

#61 Combine All Scenes
  SUIKA-GAME/Assets/Scenes/GameOver.unity
  SUIKA-GAME/Assets/Scenes/Ingame SH.unity
  SUIKA-GAME/Assets/Scenes/Option.unity
  SUIKA-GAME/Assets/Scenes/Option.unity.meta
  SUIKA-GAME/Assets/Scripts/FlashTextEffectUI.cs
  SUIKA-GAME/Assets/Scripts/GameOverLineManager.cs
  SUIKA-GAME/Assets/Scripts/PlanetDatabase.cs
  SUIKA-GAME/Assets/Scripts/SceneController.cs
  SUIKA-GAME/Assets/Scripts/SceneController.cs.meta
  SUIKA-GAME/Assets/Scripts/ScoreManager.cs
  SUIKA-GAME/Assets/Scripts/ShooterController.cs
  SUIKA-GAME/Assets/Scripts/ShowPrevPlanetUI.cs
Labels: enhancement

#65 게임내 필요한 사운드 에셋 추가
  SUIKA-GAME/Assets/Resources/Sounds.meta
  SUIKA-GAME/Assets/Resources/Sounds/게임오버 효과음.ogg
  SUIKA-GAME/Assets/Resources/Sounds/게임오버 효과음.ogg.meta
  SUIKA-GAME/Assets/Resources/Sounds/경고음.mp3
  SUIKA-GAME/Assets/Resources/Sounds/경고음.mp3.meta
  SUIKA-GAME/Assets/Resources/Sounds/마우스 오버 효과음.mp3
  SUIKA-GAME/Assets/Resources/Sounds/마우스 오버 효과음.mp3.meta
  SUIKA-GAME/Assets/Resources/Sounds/마우스 클릭 효과음.mp3
  SUIKA-GAME/Assets/Resources/Sounds/마우스 클릭 효과음.mp3.meta
  SUIKA-GAME/Assets/Resources/Sounds/배경음악2.mp3
  SUIKA-GAME/Assets/Resources/Sounds/배경음악2.mp3.meta
  SUIKA-GAME/Assets/Resources/Sounds/장면전환.mp3
  SUIKA-GAME/Assets/Resources/Sounds/장면전환.mp3.meta
  SUIKA-GAME/Assets/Resources/Sounds/행성 나갈때 효과음.mp3
  SUIKA-GAME/Assets/Resources/Sounds/행성 나갈때 효과음.mp3.meta
  SUIKA-GAME/Assets/Resources/Sounds/행성 나갈때 효과음2.mp3
  SUIKA-GAME/Assets/Resources/Sounds/행성 나갈때 효과음2.mp3.meta
  SUIKA-GAME/Assets/Resources/Sounds/행성 충돌(합체)할때 효과음.mp3
  SUIKA-GAME/Assets/Resources/Sounds/행성 충돌(합체)할때 효과음.mp3.meta
Labels: enhancement

#64 Add Planet LevelUp Score Logic
  SUIKA-GAME/Assets/Prefabs/Planet/Planet.prefab
  SUIKA-GAME/Assets/Scenes/GameOver.unity
  SUIKA-GAME/Assets/Scenes/Ingame.unity
  SUIKA-GAME/Assets/Scripts/GameOverLineManager.cs
  SUIKA-GAME/Assets/Scripts/PlanetController.cs
  SUIKA-GAME/Assets/Scripts/SceneController.cs
  SUIKA-GAME/Assets/Scripts/ScoreManager.cs
  SUIKA-GAME/Assets/Scripts/ShooterController.cs
  SUIKA-GAME/ProjectSettings/EditorBuildSettings.asset
Labels: bug, enhancement

#67 Modify Planet Collider And Fix Score Logic BUG
  SUIKA-GAME/Assets/Scripts/PlanetController.cs
  SUIKA-GAME/Assets/Scripts/SceneController.cs
  SUIKA-GAME/Assets/Scripts/ScoreManager.cs
Labels: enhancement

#71 Create Game Setting UI
  SUIKA-GAME/Assets/Scenes/Option.unity
  SUIKA-GAME/Assets/Scenes/Planet.unity
  SUIKA-GAME/Assets/Scenes/Planet.unity.meta
  SUIKA-GAME/Assets/Scripts/SceneController.cs
  SUIKA-GAME/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#70 사운드매니저 추가
  SUIKA-GAME/Assets/Scenes/Title.unity
  SUIKA-GAME/Assets/Scripts/SoundManager.cs
  SUIKA-GAME/Assets/Scripts/SoundManager.cs.meta
Labels: enhancement

#73 Modify Sound System And Add Game Option Logic
  SUIKA-GAME/Assets/Resources/Sounds/BackgroundSound-배경음.mp3
  SUIKA-GAME/Assets/Resources/Sounds/BackgroundSound-배경음.mp3.meta
  SUIKA-GAME/Assets/Resources/Sounds/GameOverSound-효과음.mp3
  SUIKA-GAME/Assets/Resources/Sounds/GameOverSound-효과음.mp3.meta
  SUIKA-GAME/Assets/Resources/Sounds/MouseClickSound-효과음.mp3
  SUIKA-GAME/Assets/Resources/Sounds/MouseClickSound-효과음.mp3.meta
  SUIKA-GAME/Assets/Resources/Sounds/MouseCursorSound-효과음.mp3
  SUIKA-GAME/Assets/Resources/Sounds/MouseCursorSound-효과음.mp3.meta
  SUIKA-GAME/Assets/Resources/Sounds/PlanetLevelUpSound-효과음.mp3
  SUIKA-GAME/Assets/Resources/Sounds/PlanetLevelUpSound-효과음.mp3.meta
  SUIKA-GAME/Assets/Resources/Sounds/PlanetOutSound-효과음.mp3
  SUIKA-GAME/Assets/Resources/Sounds/PlanetOutSound-효과음.mp3.meta
  SUIKA-GAME/Assets/Resources/Sounds/PlanetShootSound-효과음.mp3
  SUIKA-GAME/Assets/Resources/Sounds/PlanetShootSound-효과음.mp3.meta
  SUIKA-GAME/Assets/Resources/Sounds/SceneChangeSound-효과음.mp3
  SUIKA-GAME/Assets/Resources/Sounds/SceneChangeSound-효과음.mp3.meta
  SUIKA-GAME/Assets/Resources/Sounds/WarnAlertSound-효과음.mp3
  SUIKA-GAME/Assets/Resources/Sounds/WarnAlertSound-효과음.mp3.meta
  SUIKA-GAME/Assets/Resources/Sounds/게임오버 효과음.ogg
  SUIKA-GAME/Assets/Resources/Sounds/경고음.mp3
  SUIKA-GAME/Assets/Resources/Sounds/배경음악2.mp3
  SUIKA-GAME/Assets/Resources/Sounds/행성 나갈때 효과음.mp3
  SUIKA-GAME/Assets/Resources/Sounds/행성 나갈때 효과음2.mp3
  SUIKA-GAME/Assets/Resources/Sounds/행성 충돌(합체)할때 효과음.mp3
  SUIKA-GAME/Assets/Scenes/GameOver.unity
  SUIKA-GAME/Assets/Scenes/Ingame YS.unity
  SUIKA-GAME/Assets/Scenes/Ingame YS.unity.meta
  SUIKA-GAME/Assets/Scenes/Ingame.unity
  SUIKA-GAME/Assets/Scenes/Option.unity
  SUIKA-GAME/Assets/Scenes/Title.unity
  SUIKA-GAME/Assets/Scripts/CSVReader.cs
  SUIKA-GAME/Assets/Scripts/FlashTextEffectUI.cs
  SUIKA-GAME/Assets/Scripts/GameOverLineManager.cs
  SUIKA-GAME/Assets/Scripts/MouseUIController.cs
  SUIKA-GAME/Assets/Scripts/MouseUIController.cs.meta
  SUIKA-GAME/Assets/Scripts/OptionManager.cs
  SUIKA-GAME/Assets/Scripts/OptionManager.cs.meta
  SUIKA-GAME/Assets/Scripts/PlanetController.cs
  SUIKA-GAME/Assets/Scripts/SceneController.cs
  SUIKA-GAME/Assets/Scripts/ShooterController.cs
  SUIKA-GAME/Assets/Scripts/ShowPrevPlanetUI.cs
  SUIKA-GAME/Assets/Scripts/SoundManager.cs
Labels: enhancement

#75 Add Shooter Animation Logic
  SUIKA-GAME/Assets/Prefabs/Planet/Planet.prefab
  SUIKA-GAME/Assets/Resources/Sounds/ShooterLandSound-효과음.mp3
  SUIKA-GAME/Assets/Resources/Sounds/ShooterLandSound-효과음.mp3.meta
  SUIKA-GAME/Assets/Resources/Sounds/ShooterTakeoffSound-효과음.mp3
  SUIKA-GAME/Assets/Resources/Sounds/ShooterTakeoffSound-효과음.mp3.meta
  SUIKA-GAME/Assets/Scenes/Ingame.unity
  SUIKA-GAME/Assets/Scripts/ShooterAnimationController.cs
  SUIKA-GAME/Assets/Scripts/ShooterAnimationController.cs.meta
  SUIKA-GAME/Assets/Scripts/ShooterController.cs
  SUIKA-GAME/Assets/Scripts/SoundManager.cs
Labels: enhancement

#80 Modify Shooter Logic And Animation
  SUIKA-GAME/Assets/Prefabs/Planet/Planet.prefab
  SUIKA-GAME/Assets/Scenes/Ingame.unity
  SUIKA-GAME/Assets/Scenes/Title.unity
  SUIKA-GAME/Assets/Scripts/ShooterAnimationController.cs
  SUIKA-GAME/Assets/Scripts/ShooterController.cs
  SUIKA-GAME/Assets/Scripts/ShowGameOverUI.cs
  SUIKA-GAME/Assets/Scripts/ShowGameOverUI.cs.meta
Labels: enhancement

#82 Merge Repogitory Files
  SUIKA-GAME/Assets/Scenes/1.Title.unity
  SUIKA-GAME/Assets/Scenes/1.Title.unity.meta
  SUIKA-GAME/Assets/Scenes/2.Option.unity
  SUIKA-GAME/Assets/Scenes/2.Option.unity.meta
  SUIKA-GAME/Assets/Scenes/3.GameOver.unity
  SUIKA-GAME/Assets/Scenes/3.GameOver.unity.meta
  SUIKA-GAME/Assets/Scenes/4.Ingame.unity
  SUIKA-GAME/Assets/Scenes/4.Ingame.unity.meta
  SUIKA-GAME/Assets/Scenes/GameOver.unity
  SUIKA-GAME/Assets/Scenes/Ingame.unity
  SUIKA-GAME/Assets/Scenes/Option.unity
  SUIKA-GAME/Assets/Scenes/Title.unity
  SUIKA-GAME/Assets/Scripts/GameOverLineManager.cs
  SUIKA-GAME/Assets/Scripts/MouseUIController.cs
  SUIKA-GAME/Assets/Scripts/ShowGameOverUI.cs
Labels: duplicate

#84 금성 이미지 및 파티클 매니저 구현
  SUIKA-GAME/Assets/Resources/DataSheets/PlanetInfoSheet.csv
  SUIKA-GAME/Assets/Resources/Sounds/GameStartSound-효과음.mp3
  SUIKA-GAME/Assets/Resources/Sounds/GameStartSound-효과음.mp3.meta
  SUIKA-GAME/Assets/Resources/Sprites/Venus.png
  SUIKA-GAME/Assets/Resources/Sprites/Venus.png.meta
  SUIKA-GAME/Assets/Scenes/Title.unity
  SUIKA-GAME/Assets/Scripts/ParticleManager.cs
  SUIKA-GAME/Assets/Scripts/ParticleManager.cs.meta
  SUIKA-GAME/Assets/Scripts/ShooterAnimationController.cs
  SUIKA-GAME/Assets/Scripts/SoundManager.cs
Labels: bug, enhancement

#87 인게임 옵션 추가 및 충돌 로직 간소화
  SUIKA-GAME/Assets/Physics/Planet.physicsMaterial2D
  SUIKA-GAME/Assets/Prefabs/Planet/Planet.prefab
  SUIKA-GAME/Assets/Scenes/Ingame.unity
  SUIKA-GAME/Assets/Scenes/Option.unity
  SUIKA-GAME/Assets/Scripts/CSVReader.cs
  SUIKA-GAME/Assets/Scripts/GameOverLineManager.cs
  SUIKA-GAME/Assets/Scripts/OptionManager.cs
  SUIKA-GAME/Assets/Scripts/ParticleManager.cs
  SUIKA-GAME/Assets/Scripts/PlanetController.cs
  SUIKA-GAME/Assets/Scripts/PlanetDatabase.cs
  SUIKA-GAME/Assets/Scripts/ShooterAnimationController.cs
  SUIKA-GAME/Assets/Scripts/ShooterController.cs
  SUIKA-GAME/Assets/Scripts/SoundManager.cs
Labels: enhancement

#88 인게임씬과 게임오버씬의 스코어점수 위치수정
  SUIKA-GAME/Assets/Scenes/GameOver.unity
  SUIKA-GAME/Assets/Scenes/Ingame.unity
Labels: enhancement

#92 Modify Blink Text Logic And Initialize
  SUIKA-GAME/Assets/Scenes/GameOver.unity
  SUIKA-GAME/Assets/Scenes/Ingame.unity
  SUIKA-GAME/Assets/Scenes/Title.unity
  SUIKA-GAME/Assets/Scripts/ShowGameOverUI.cs
  SUIKA-GAME/Assets/Scripts/ShowPrevPlanetUI.cs
  SUIKA-GAME/Assets/Scripts/TextBlinkUI.cs
  SUIKA-GAME/Assets/Scripts/TextBlinkUI.cs.meta
Labels: enhancement

#93 Merge Repogitory Files
  SUIKA-GAME/Assets/Scenes/Title.unity
Labels: duplicate

#95 모든씬 배경에 별똥별 이펙트 추가
  SUIKA-GAME/Assets/Prefabs/Particle/Materials/DebrisParticle.mat
  SUIKA-GAME/Assets/Prefabs/Particle/Materials/Lightning.mat
  SUIKA-GAME/Assets/Prefabs/Particle/Materials/MediumFlame03.mat
  SUIKA-GAME/Assets/Scenes/Ingame YS.unity
  SUIKA-GAME/Assets/Scenes/Ingame YS.unity.meta
  SUIKA-GAME/Assets/Scenes/Title.unity
Labels: enhancement

#97 2P 인게임씬 추가
  SUIKA-GAME/Assets/Scenes/2P Ingame.unity
  SUIKA-GAME/Assets/Scenes/2P Ingame.unity.meta
Labels: enhancement

#98 Merge Repogitory Files
  SUIKA-GAME/Assets/Scenes/2P Ingame SH.unity
  SUIKA-GAME/Assets/Scenes/2P Ingame SH.unity.meta
  SUIKA-GAME/Assets/Scripts/1P.meta
  SUIKA-GAME/Assets/Scripts/1P/GameOverLineManager.cs
  SUIKA-GAME/Assets/Scripts/1P/GameOverLineManager.cs.meta
  SUIKA-GAME/Assets/Scripts/1P/ScoreManager.cs
  SUIKA-GAME/Assets/Scripts/1P/ScoreManager.cs.meta
  SUIKA-GAME/Assets/Scripts/1P/ShooterController.cs
  SUIKA-GAME/Assets/Scripts/1P/ShooterController.cs.meta
  SUIKA-GAME/Assets/Scripts/1P/ShowPrevPlanetUI.cs
  SUIKA-GAME/Assets/Scripts/1P/ShowPrevPlanetUI.cs.meta
  SUIKA-GAME/Assets/Scripts/2P.meta
  SUIKA-GAME/Assets/Scripts/2P/GameOverLineManager2P.cs
  SUIKA-GAME/Assets/Scripts/2P/GameOverLineManager2P.cs.meta
  SUIKA-GAME/Assets/Scripts/2P/ScoreManager2P.cs
  SUIKA-GAME/Assets/Scripts/2P/ScoreManager2P.cs.meta
  SUIKA-GAME/Assets/Scripts/2P/ShooterController2P.cs
  SUIKA-GAME/Assets/Scripts/2P/ShooterController2P.cs.meta
  SUIKA-GAME/Assets/Scripts/2P/ShowPrevPlanetUI2P.cs
  SUIKA-GAME/Assets/Scripts/2P/ShowPrevPlanetUI2P.cs.meta
  SUIKA-GAME/Assets/Scripts/FileReader.meta
  SUIKA-GAME/Assets/Scripts/FileReader/CSVReader.cs
  SUIKA-GAME/Assets/Scripts/FileReader/CSVReader.cs.meta
  SUIKA-GAME/Assets/Scripts/GameOverController.cs
  SUIKA-GAME/Assets/Scripts/GameOverController.cs.meta
  SUIKA-GAME/Assets/Scripts/OptionController.cs
  SUIKA-GAME/Assets/Scripts/OptionController.cs.meta
  SUIKA-GAME/Assets/Scripts/PlanetController.cs
Labels: duplicate

#102 2P GameOver와 UI기능 구현
  SUIKA-GAME/Assets/Scenes/GameOver.unity
  SUIKA-GAME/Assets/Scenes/Ingame.unity
  SUIKA-GAME/Assets/Scenes/Ingame2P.unity
  SUIKA-GAME/Assets/Scenes/Option.unity
  SUIKA-GAME/Assets/Scripts/2P/GameOverLineManager2P.cs
  SUIKA-GAME/Assets/Scripts/GameOverController.cs
  SUIKA-GAME/Assets/Scripts/SceneController.cs
Labels: enhancement

#104 게임 설정 재구현
  SUIKA-GAME/Assets/Scenes/Ingame.unity
  SUIKA-GAME/Assets/Scenes/Ingame2P.unity
  SUIKA-GAME/ProjectSettings/BurstAotSettings_StandaloneWindows.json
  SUIKA-GAME/ProjectSettings/CommonBurstAotSettings.json
  SUIKA-GAME/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement
